### ISSUE TITLE
AdMob crashlytics Warning

### ISSUE THREAD

**Issue by holyspidoo** [kiwi-bop/flutter_crashlytics#11]
Wanted to know if we should worry about this. I'm using Crashlytics, and Admob, and your awesome flutter_crashlytics. I get this while running the app on iOS simulator:

`[Crashlytics:Crash] Warning: NSUncaughtExceptionHandler is 'GADOCategories_GADOSlot_AdEvents'`

Should I worry or can I just safely ignore? Everything seems to be working fine so I'm ignoring right now :)

**Comment by jaumard** [comment]
I don't know enough Crashlytics to answer that sorry, if anyone pass by and know this please share ^^
But if you didn't notice any weird behavior just ignore it for now (also it's "just" a warning so...)

**Comment by holyspidoo** [comment]
Ignoring warnings is what I do best!

**Comment by jaumard** [comment]
Closing this as it should be good ^^
