### ISSUE TITLE
Plugin not building for objective-c based Flutter iOS projects

### ISSUE THREAD

**Issue by mikedev13** [kiwi-bop/flutter_crashlytics#17]
Plugin is building fine following the setup instructions for Swift based Flutter iOS code. But get "The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor." when adding the plugin to an objective-c based Flutter iOS code.  Please advise on how to use with objective-c based Flutter iOS code.

**Comment by jaumard** [comment]
Some users already has this error and describe the way of get rid of it here https://github.com/kiwi-bop/flutter_crashlytics/issues/3
