### ISSUE TITLE
Opt Out option due to GDPR and Play Store

### ISSUE THREAD

**Issue by jaggernod** [kiwi-bop/flutter_crashlytics#18]
I have just gotten a mail from Play Store that my app is sending **Advertisement ID**. 
I do not have ads in my application. 
After further investigation, I noticed that Crashlytics is collecting the ID. 
There is no way of disabling the behaviour. 
The only way is to have Opt-Out/In feature [implemented](https://docs.fabric.io/android/crashlytics/advanced-setup.html#enable-opt-in-reporting).

@jaumard  I can implement it for Android but I do not own Mac so cannot check it for iOS. Would you implement it there? I'm sure that lots of European devs will have the same issue soon.

**Comment by jaumard** [comment]
Hi @jaggernod :)

That's true :/ so the purpose will be I guess to add a new method `startReporting` and then you can on your app dart code call it once you've check your Opt-Out/In flag. 

But this also mean that until your users has checked this Opt-Out/In flag you'll not have any crash reporting... so if your app crash directly when it start you'll not receive any reports...

**Comment by jaggernod** [comment]
Yep, exactly. I wouldn't want to store the user's decision on the plugin's side.

**Comment by jaggernod** [comment]
Will create a PR

**Comment by jaumard** [comment]
Published as 0.1.0, thanks for your help :)

**Comment by haart28** [comment]
@jaumard Could you please update Android-related section in docs according to this changes?
It is not clear for me how for to opt-out in Android, but I see how to do in iOS:

> Turn off automatic collection with a new key to your Info.plist file (GDPR compliency if you want it):
> Key: firebase_crashlytics_collection_enabled
> Value: false

**Comment by jaumard** [comment]
you have nothing to do for Android :) it's done by the plugin so nothing to update
