### ISSUE TITLE
[!] Unable to determine Swift version for the following pods:

### ISSUE THREAD

**Issue by guitcastro** [kiwi-bop/flutter_crashlytics#22]
I tried to add the pod using Xcode10, but I got this error:

[!] Unable to determine Swift version for the following pods:

 - `flutter_crashlytics` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by guitcastro** [comment]
Fixed by creating an empty swift file in the project.

**Comment by guitcastro** [comment]
> > Fixed by creating an empty swift file in the project.
> 
> hi, I'm new to xcode and experiencing this issue, can you provide steps to implement this solution?

Just open the iOS project in the folder `ios/Runner/Runner.xcworkspace` with xcode and then just add a new swift file anywhere, xcode will automatic apply the changes need to your project support swift.

**Comment by jaumard** [comment]
Shouldn't be needed anymore as the last version of the plugin is in full objective C, there no more swift in it. Might be another plugin or you are not using the last version

**Comment by lipengda** [comment]
> > > Fixed by creating an empty swift file in the project.
> > 
> > 
> > hi, I'm new to xcode and experiencing this issue, can you provide steps to implement this solution?
> 
> Just open the iOS project in the folder `ios/Runner/Runner.xcworkspace` with xcode and then just add a new swift file anywhere, xcode will automatic apply the changes need to your project support swift.

thanks

**Comment by srijankrs** [comment]
> > > Fixed by creating an empty swift file in the project.
> > 
> > 
> > hi, I'm new to xcode and experiencing this issue, can you provide steps to implement this solution?
> 
> Just open the iOS project in the folder `ios/Runner/Runner.xcworkspace` with xcode and then just add a new swift file anywhere, xcode will automatic apply the changes need to your project support swift.

hats off buddy !!

**Comment by joriki** [comment]
You can set the Swift version by including e.g. `ENV['SWIFT_VERSION'] = '3'` at the top of your `Podfile`.

**Comment by mettini** [comment]
@joriki's solution worked for me!
