### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "Fabric":

### ISSUE THREAD

**Issue by guitcastro** [kiwi-bop/flutter_crashlytics#23]
[!] CocoaPods could not find compatible versions for pod "Fabric":
  In snapshot (Podfile.lock):
    Fabric (= 1.7.13, ~> 1.7.13)

  In Podfile:
    flutter_crashlytics (from `.symlinks/plugins/flutter_crashlytics/ios`) was resolved to 0.0.1, which depends on
      Fabric

It seems like you've changed the constraints of dependency `Fabric` inside your development pod `flutter_crashlytics`.
You should run `pod update Fabric` to apply changes you've made.

**Comment by jaumard** [comment]
The plugin doesn't contains any Podflie https://github.com/kiwi-bop/flutter_crashlytics/tree/master/ios
I only have a pod spec https://github.com/kiwi-bop/flutter_crashlytics/blob/master/ios/flutter_crashlytics.podspec but no version specified 
My recent changes was only for Android not iOS.

**Comment by guitcastro** [comment]
I reinstall the plugin and now it's working
