### ISSUE TITLE
error: Value for SWIFT_VERSION cannot be empty. (in target 'flutter_crashlytics')

### ISSUE THREAD

**Issue by philipgiuliani** [kiwi-bop/flutter_crashlytics#25]
Hi, I a, getting this error when trying to build the iOS Project.

```
error: Value for SWIFT_VERSION cannot be empty. (in target 'flutter_crashlytics') 
```

When opening it with XCode the following error came up:
![bildschirmfoto 2018-10-19 um 10 27 29](https://user-images.githubusercontent.com/5446019/47206724-a5c60b00-d389-11e8-86b1-7d8c0cbac949.png)

**Comment by jaumard** [comment]
You need to specify the swift version on your project check https://github.com/kiwi-bop/flutter_crashlytics/issues/22 and https://github.com/kiwi-bop/flutter_crashlytics/issues/3
