### ISSUE TITLE
Can I use the version of Objective-C?

### ISSUE THREAD

**Issue by yy1300326388** [kiwi-bop/flutter_crashlytics#3]
I have the same error as this problem.
[https://github.com/flutter/flutter/issues/9694](https://github.com/flutter/flutter/issues/9694)
[https://github.com/flutter/flutter/issues/20045](https://github.com/flutter/flutter/issues/20045)
[https://github.com/apptreesoftware/flutter_google_map_view/issues/82#issuecomment-408303979](https://github.com/apptreesoftware/flutter_google_map_view/issues/82#issuecomment-408303979)

**Comment by jaumard** [comment]
Hello @yy1300326388 

Did you add `use_frameworks!` on your pod file of your app ? If you're under a framework, you can't use this plugin because of limitation on cocoa pods that doesn't get the transitive dependancies on nested frameworks.

**Comment by yy1300326388** [comment]
@jaumard 

If I add `use_frameworks!`, there will be other errors. And I saw that it could not be solved. I am not very familiar with iOS, if you can come to an Objective-C version, thank you very much.

**Comment by pcejas** [comment]
Same here. Enabling use_framework! Breaks google maps and other things.

Objective C version would be really nice.

El 7 sep. 2018 03:32, "Sean" <notifications@github.com> escribió:

@jaumard <https://github.com/jaumard>

If I add use_frameworks!, there will be other errors. And I saw that it
could not be solved. I am not very familiar with iOS, if you can come to an
Objective-C version, thank you very much.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kiwi-bop/flutter_crashlytics/issues/3#issuecomment-419337530>,
or mute the thread

**Comment by jaumard** [comment]
I'll not have the time to transpose the plugin in ObjC, but PR are welcome if you're sure it will fix your problem.

**Comment by bjon** [comment]
I have the same problem (build error on ios). Its sad cause its working so great on android.

**Comment by jaumard** [comment]
I'm using this plugin with firebase_analytics google_sign_in and just try to add google_maps_flutter on my pub spec and I'm still able to build and launch the app... That's strange

**Comment by bjon** [comment]
Even with a new project with `flutter_crashlytics` as the only depencency, build still fails.
See [build-output](https://gist.github.com/bjon/f16b98039b1725528e25e8ac954e0335).

When switching to `geolocator` (also a swift plugin) the build succeeds.

pubspec.yml
```
name: ft
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_crashlytics: ^0.0.6
  # geolocator: ^2.0.1
```

Podfile
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2' # 3.0, 4.0, 4.2
    end
  end
end
```

**Comment by jaumard** [comment]
because you miss `use_frameworks!` on PodFile, the `use_frameworks!` is mandatory for this library to works because of bundle static libraries.

**Comment by yy1300326388** [comment]
@bjon  
I just encountered this problem last week, I spent 2 days to solve it, I am a new iOS, this problem appears in the Object-C and Swift plug-in hybrid project, just need to create a new in the Runner directory of the Xcode project Just a Swift file.

![object-c swift swift](https://user-images.githubusercontent.com/8764899/46012417-c046f480-c0fb-11e8-82f1-d5fb74c926a3.png)

```
CMD+N
```
![swift](https://user-images.githubusercontent.com/8764899/46012528-26cc1280-c0fc-11e8-87cd-c9cbff4167a5.png)

![swift 1](https://user-images.githubusercontent.com/8764899/46012534-2b90c680-c0fc-11e8-9078-fe0b2753db06.png)

**Comment by jaumard** [comment]
Or create a project with Swift support from the start. Adding a swift file on existing project enable the swift support that's why it's working. But `use_framework!` still need to be added :) 
I'm closing this issue as it works as expected on project with Swift enabled. If an objective C version is really needed PR are welcome :)

**Comment by bjon** [comment]
> because you miss `use_frameworks!` on PodFile, the `use_frameworks!` is mandatory for this library to works because of bundle static libraries.

Its in the Podfile
```
target 'Runner' do
  use_frameworks!
```

**Comment by bjon** [comment]
Do you mean it has to be in the top of the file?

**Comment by jaumard** [comment]
I put it at the top of the file personally

**Comment by bjon** [comment]
> @bjon
> I just encountered this problem last week, I spent 2 days to solve it, I am a new iOS, this problem appears in the Object-C and Swift plug-in hybrid project, just need to create a new in the Runner directory of the Xcode project Just a Swift file.
> 
> ![object-c swift swift](https://user-images.githubusercontent.com/8764899/46012417-c046f480-c0fb-11e8-82f1-d5fb74c926a3.png)
> 
> ```
> CMD+N
> ```
> ![swift](https://user-images.githubusercontent.com/8764899/46012528-26cc1280-c0fc-11e8-87cd-c9cbff4167a5.png)
> 
> ![swift 1](https://user-images.githubusercontent.com/8764899/46012534-2b90c680-c0fc-11e8-9078-fe0b2753db06.png)

Now it works! Thanks alot!!
