### ISSUE TITLE
iOS App is not staring in release mode

### ISSUE THREAD

**Issue by eikebartels** [kiwi-bop/flutter_crashlytics#31]
After releasing the app, the app is not staring anymore if I add Crashlytics like it is described in the readme

**Comment by jaumard** [comment]
Are you using Fabric or Firebase for crashlytics ?

**Comment by pboos** [comment]
I have to say the iOS setup instructions are not that good anyway ;-). Would probably be nice to update it to a little clearer instructions.

1. Not sure what I have to do in the build phase. Text & image do not really say the same thing. And then the xcode 10 note is not clear. What needs to be done on xcode 10?
2. "Then on your Podfile add use_frameworks!" is that as well if one didn't do the things before it (not fabric and not disabling automatic collection)

If you want I can as well create a new issue for this. But thought this might be related.

**Comment by jaumard** [comment]
Closing as no news, please provide a small example to reproduce the problem.
