### ISSUE TITLE
Application not running in iOS 

### ISSUE THREAD

**Issue by vipinagrahari** [kiwi-bop/flutter_crashlytics#36]
I am trying to run my app into iOS simulator and I am getting following error. 

`Terminating app due to uncaught exception 'FABException', reason:
'[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.' `

I have integated Firebase crashlytics and not Fabric so I am not able to understand what is causing this error. Any help will be appreciated.

**Comment by jaumard** [comment]
Duplicate of #27
