### ISSUE TITLE
Logging non-fatal exceptions

### ISSUE THREAD

**Issue by jaggernod** [kiwi-bop/flutter_crashlytics#4]
Sometimes there are exceptions that do/should not crash the applications. 
Would be great if there was the possibility of logging it with `Crashlitics::logException`.

**Comment by jaumard** [comment]
So basically a use case of this would be to try/catch something and be able to send manually the exception to Crashlytics by a flutter method `logException`, is it what you want ?

**Comment by jaggernod** [comment]
Yes, exactly.

**Comment by jaumard** [comment]
Ok :) it can be a good feature to add. If you think you can do it PR are welcome, if not I'll try to add this when I have time

**Comment by jaggernod** [comment]
If it's fine I can provide PR for Android but not for iOS.

**Comment by jaumard** [comment]
It's fine, I'll update your PR with iOS side before merging :) but Swift and Kotlin are very similar so shouldn't be that different ^^

**Comment by jaggernod** [comment]
Sounds good! Will provide the PR when I have some idle time.

**Comment by jaumard** [comment]
Android part done #7 :) iOS to go now

**Comment by jaumard** [comment]
@jaggernod I'm doing the iOS side and in fact by using the API I notice that `logError` and `logException` are maybe not needed... 

I just add a `reportError()` method to be able to support Zone reporting, so it mean that it will do same as `logError` and `logException`... 

So my idea is to remove those and just have an reportError (who can handle exception or error).
What do you think ? 

Basically now the `main` will look like this: 
```
void main() {
  bool isInDebugMode = false;

  FlutterError.onError = (FlutterErrorDetails details) {
    if (isInDebugMode) {
      // In development mode simply print to console.
      FlutterError.dumpErrorToConsole(details);
    } else {
      // In production mode report to the application zone to report to
      // Crashlytics.
      Zone.current.handleUncaughtError(details.exception, details.stack);
    }
  };

  runZoned<Future<Null>>(() async {
    runApp(MyApp());
  }, onError: (error, stackTrace) async {
    // Whenever an error occurs, call the `reportCrash` function. This will send
    // Dart errors to our dev console or Crashlytics depending on the environment.
    await FlutterCrashlytics().reportCrash(error, stackTrace, forceCrash: false);
  });
}
```

**Comment by jaumard** [comment]
Maybe you'll want an alias like `logCrash` ? but in the end the implementation is the same ^^ it's just that manual logging is like `forceCrash=false`

**Comment by jaumard** [comment]
I've push this concept here https://github.com/kiwi-bop/flutter_crashlytics/commit/06d61e19438ced51b755c23253bf8bdb5b55520f can you please try it and let me know what you think of it ?

**Comment by jaumard** [comment]
Published as 0.0.6 :)

**Comment by shyjuzz** [comment]
@jaumard 

Thank you for the plugin. Unfortunately, I am not able to see the non-fatal exceptions logged using the below lines of code in the crashlytics dashboard. What may be wrong here?

FlutterCrashlytics().log('My loogggg', priority: 200, tag: 'test');
                  FlutterCrashlytics().logException(error, error.stackTrace);

but the crashed are recorded if the  `forcecrash `is true

**Comment by jaumard** [comment]
non-fatal exceptions are saved by crashlytics library and send periodically to crashlytics dashboard, so you might want to restart your app or wait a bit to see non fatal exceptions

**Comment by shyjuzz** [comment]
@jaumard Thank you for the reply. I couldnt see the non-fatal exception in the dashborad after 3 days as well and my project is working fine in the debug mode but gettiing the following exception in the release mode. 
Please help
```

`* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :flutter_crashlytics.
     Required by:
         project :app
      > Could not select value from candidates [null, debug, release] using AlternateDisambiguationRule.BuildTypeRule.
         > java.lang.NullPointerException (no error message)`
```
