### ISSUE TITLE
Crash in background isolate

### ISSUE THREAD

**Issue by rostopira** [kiwi-bop/flutter_crashlytics#40]
My flutter app is running in background, so activity is null, only context available
On start (push notification) it crashes app with NPE

**Comment by jaumard** [comment]
Ho never use it that way, can you provide a small example to reproduce the problem ? It would help a lot to fix this. :)

**Comment by rostopira** [comment]
Example would be quite big, and unnecessary
Just keep in mind, that `registrar.activity()` is nullable
