### ISSUE TITLE
Not Reporting "Logs" in Android

### ISSUE THREAD

**Issue by kaumudpa** [kiwi-bop/flutter_crashlytics#42]
Hello,

we are able to see the stacktraces, but The plugin is not reporting `logs` and `setuserinfo` to the firebase console of android crashes even after using `log(String msg, {int priority, String tag})` - It is working perfectly fine in ios. 
Also how to set and report multiple key/value pairs ?

my code in main.dart:
```
await FlutterCrashlytics()
       .reportCrash( error, stackTrace, forceCrash: true /* ConstantUtil.force_crash */);
   await FlutterCrashlytics().setInfo('Handle_Id', prefer.getString("handle"));
   await FlutterCrashlytics().setUserInfo('PageName_handle', 'Search_User',prefer.getString("handle"));
   await FlutterCrashlytics().log("error.toString()",priority: 1);
```

**Comment by jaumard** [comment]
I have no problem on Android, but you might want to first set info and log and after reporting the crash.

```
await FlutterCrashlytics().setInfo('Handle_Id', prefer.getString("handle"));
await FlutterCrashlytics().setUserInfo('PageName_handle', 'Search_User',prefer.getString("handle"));
await FlutterCrashlytics().log("error.toString()",priority: 1);
await FlutterCrashlytics()
       .reportCrash( error, stackTrace, forceCrash: true /* ConstantUtil.force_crash */);
```
even more if you forceCrash or the other method might not be executed. I guess on iOS it has time to execute them but not Android. 
Let me know :)

**Comment by kaumudpa** [comment]
Let me give it a try!

**Comment by kaumudpa** [comment]
Yes It is reporting now! Any suggestions what should i pass in:  `await FlutterCrashlytics().log();` so that i can get proper log of the crash?

**Comment by jaumard** [comment]
you don't need `FlutterCrashlytics().log ` to have log of the crash, has you already pass the stack trace when you use `reportCrash`,  `log` is for adding more logs to that stack trace, for example if you want to dump your http calls or your redux action/state for it to be available on crashlytics logs tab. That's it :)

**Comment by chetan-cueclad** [comment]
Thank you for this amazing plugin! We can close this issue :)

**Comment by jaumard** [comment]
Glad it worked :)
