### ISSUE TITLE
Why are you using swift??

### ISSUE THREAD

**Issue by long1eu** [kiwi-bop/flutter_crashlytics#43]
https://github.com/flutter/flutter/issues/17999

**Comment by rostopira** [comment]
Because Objective-C sucks, obviously

**Comment by long1eu** [comment]
I agree, but still the size difference is huge.

**Comment by jaumard** [comment]
Didn't see this issue before doing this repo, and learn with pain that plugin in swift/kotlin sucks all their life of compatibility problems, I'll probably never do a plugin in swift/kotlin again... but now it's done and I don't have time to switch back to objectiveC/Java. If some contributors want to do this job I'll gladly review and merge it ! But on my side it's working fine like this

**Comment by miguelcmedeiros** [comment]
Are you planning to also move from Kotlin to Java?
Given the compatibility issues with Kotlin versions, that would be great 😊

**Comment by jaumard** [comment]
Totally agree @miguelcmedeiros but I'll reply the same thing as @long1eu :) I don't plan on doing it as I have no problem with it and don't have time to do the move, but I'm open to contribution and will review/test/merge a PR for that ;)
