### ISSUE TITLE
Error occurred sending report com.crashlytics.android.core.SessionReport

### ISSUE THREAD

**Issue by annalaufey** [kiwi-bop/flutter_crashlytics#44]
I keep getting these errors in my logs
E/Fabric  (15406): Settings request failed.
E/Fabric  (15406): Error performing auto configuration.
E/CrashlyticsCore(15406): Error occurred sending report com.crashlytics.android.core.SessionReport@e335cb3
E/CrashlyticsCore(15406): Error occurred sending report com.crashlytics.android.core.SessionReport@78f3270
E/CrashlyticsCore(15406): Error occurred sending report com.crashlytics.android.core.SessionReport@bf6c9e9
E/CrashlyticsCore(15406): Error occurred sending report com.crashlytics.android.core.SessionReport@ccf266e
E/CrashlyticsCore(15406): Error occurred sending report com.crashlytics.android.core.SessionReport@8fd110f
E/CrashlyticsCore(15406): Error occurred sending report com.crashlytics.android.core.SessionReport@f8d059c

These my doctor logs 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.5, on Mac OS X 10.14.2 18C54, locale en-IS)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (2 available)

• No issues found!
➜  ~ 

I'm using firebase instead of fabric.

**Comment by jaumard** [comment]
Never got that one... But look like a configuration issues, did you follow the firebase setup correctly ?

**Comment by jaumard** [comment]
Closing as no response
