### ISSUE TITLE
PlatformException during app launch

### ISSUE THREAD

**Issue by Purus** [kiwi-bop/flutter_crashlytics#45]
While launching the app, I get the below error. I want to use Firebase only and not with crashlytics. But it looks for some Crashlytics details.

```
E/flutter (28577): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (28577): PlatformException(error, This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
E/flutter (28577): install an Android build tool and ask a team member to invite you to this app's organization., null)
E/flutter (28577): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (28577): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (28577): <asynchronous suspension>
E/flutter (28577): #2      FlutterCrashlytics.initialize (package:flutter_crashlytics/flutter_crashlytics.dart:17:53)
E/flutter (28577): <asynchronous suspension>
E/flutter (28577): #3      main (package:silkthread/main.dart:37:30)
E/flutter (28577): <asynchronous suspension>
E/flutter (28577): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (28577): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Should I be changing the gradle build file even when not using Crashlytics?

**Comment by ekremkenter** [comment]
@Purus faced the same issue. Follow steps in Firebase docs ([link](https://firebase.google.com/docs/crashlytics/get-started?authuser=0#android)) documentation on this repo is missing. @kiwi-bop can you please check it?

**Comment by Purus** [comment]
I was able to solve this issue by editing Gradle build file as mentioned in
the readme. Earlier I thought it was only for fabric usage.

Thanks,

Purusothaman Ramanujam

**Comment by jaumard** [comment]
All good then :) glad it works 
@ekremkenter for now we're not using Firebase for crash reporting :/ but we'll do soon so we'll update docs if needed for this
