### ISSUE TITLE
IOS stacktrace is in multiple logs

### ISSUE THREAD

**Issue by SaltumDis** [kiwi-bop/flutter_crashlytics#47]
When IOS app crashes, stacktrace is separated into multiple logs.
Maybe it should be under one log for better readability?

Log example: 
<img width="1228" alt="screenshot 2019-01-08 at 16 49 29" src="https://user-images.githubusercontent.com/13053469/50838063-ce94e580-1365-11e9-8c29-2452c14505c7.png">

**Comment by jaumard** [comment]
Don't know why you have this but here is what I have on Crashlytics: 
<img width="1374" alt="capture d ecran 2019-01-08 a 16 08 13" src="https://user-images.githubusercontent.com/2970449/50838977-a0140c00-135f-11e9-9a0e-f6cf13c09428.png">

don't know how you can get such a screen...

**Comment by jaumard** [comment]
All this plugin do is to recreate Android or iOS exception and let fabric do his job with it so there not that much stuff I can do about the presentation. But I'm wondering where you have this layout/style

**Comment by SaltumDis** [comment]
We are using firebase crashlytics. According to README.md IOS stacktrace is in logs.

**Comment by jaumard** [comment]
Should be good on 0.2.0 version :)
