### ISSUE TITLE
Android logs have "?/" at the start of the log

### ISSUE THREAD

**Issue by SaltumDis** [kiwi-bop/flutter_crashlytics#48]
This is how IOS logs look like. At the start of the log they have severity level. 

<img width="452" alt="screenshot 2019-01-08 at 16 56 33" src="https://user-images.githubusercontent.com/13053469/50838363-8629f780-1366-11e9-8127-cfda4294cff5.png">

This is Android logs...
<img width="452" alt="screenshot 2019-01-08 at 16 55 56" src="https://user-images.githubusercontent.com/13053469/50838335-790d0880-1366-11e9-9b05-7dd26bbf8b0d.png">

**Comment by jaumard** [comment]
Yes strange, just checked and I've the same on my side... don't know why this append, I'll check this thanks for the report !

**Comment by jaumard** [comment]
So I'm guessing that it come from https://github.com/kiwi-bop/flutter_crashlytics/blob/master/android/src/main/kotlin/com/kiwi/fluttercrashlytics/FlutterCrashlyticsPlugin.kt#L49 and I think Crashlytics is expecting Android log level not Dart one. 
As a quick fix you can use in your dart code `await FlutterCrashlytics().log('${ record.level.value}: ${record.loggerName} ${record.message}');` it will produce same output. I'll try to fix this asap anyway

**Comment by SaltumDis** [comment]
Thanks!

**Comment by jaumard** [comment]
Should be good on 0.2.0 version
