### ISSUE TITLE
Crash with forceCrash not reported 

### ISSUE THREAD

**Issue by jaumard** [kiwi-bop/flutter_crashlytics#49]
Hey @long1eu I just notice that there still an issue when `forceCrash` is true, I don't receive anything on Crashlytics for those crash :/

**Comment by long1eu** [comment]
I'll take a look. We definitely need some tests.

**Comment by jaumard** [comment]
Yeah I didn't make any test as this package is supposed to be temporary until Flutter team come with an official solution (because I basically do hack to make it work) , but they take their time to do it lool

**Comment by long1eu** [comment]
:)))))

**Comment by long1eu** [comment]
can you give me access to the firebase console?
lung.razvan@gmail.com

**Comment by long1eu** [comment]
Looks like it's working.

**Comment by long1eu** [comment]
https://github.com/kiwi-bop/flutter_crashlytics/pull/50

**Comment by jaumard** [comment]
Hum I'll try again then because mine was not reported...

**Comment by long1eu** [comment]
I think that after the crash you need to reopen the app from the home screen. This will the the log.

**Comment by jaumard** [comment]
I know, but I think I didn't receive any email because the issue was existing on Crashlytics already, just checked and look like it works ! So let's deploy it ;) thanks !

**Comment by jaumard** [comment]
Don't know if you're using Firebase instead of Crashlytics but if it's the case, can you update the Readme to have the right setup steps for it ? Because there some issues about setup firebase instead of fabric with this plugin...

**Comment by long1eu** [comment]
Sure.

În joi, 10 ian. 2019, 14:04 Jaumard <notifications@github.com a scris:
