### ISSUE TITLE
dependency mismatch after upgrading to android studio 3.3

### ISSUE THREAD

**Issue by paulhsu** [kiwi-bop/flutter_crashlytics#51]
buildscript {
    ext.kotlin_version = '1.2.71'    ==> **1.3.11**
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'  ==> **3.3.0**
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

**Comment by panthe** [comment]
Yes, this issue affect our installation too

**Comment by KammererTob** [comment]
There i an open pull-request for the dependency updates:

https://github.com/kiwi-bop/flutter_crashlytics/pull/39

**Comment by amerinoo** [comment]
Good job @KammererTob that should work. Thanks!

**Comment by jaumard** [comment]
Try with 2.1, should be ok now :)

**Comment by ened** [comment]
@paulhsu please close issue if resolved.

**Comment by jaumard** [comment]
Closing this as it should be ok now, if not the case please reopen :)
