### ISSUE TITLE
[iOS] says I need to invoke FirebaseApp.configure()

### ISSUE THREAD

**Issue by jmrboosties** [kiwi-bop/flutter_crashlytics#58]
I followed the instructions in the readme, Android works fine, but on iOS I get the following message:

```The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.```

Calling FirebaseApp.configure() in the AppDelegate's `didFinishLaunchingWithOptions` makes this error go away, but leads to another problem which I'm still debugging as it might not be to do with this plugin. Are we expected to add this line, or is this indicative of me doing something wrong?

**Comment by jaumard** [comment]
Yes you need to add this live as it's firebase configuration, I just implement the fabric part in this plugin

**Comment by jmrboosties** [comment]
OK, this should probably be added to the readme then, the way it was written I assumed this action was taken by the Firebase implementation on Flutter's side.
