### ISSUE TITLE
log() Priority Levels

### ISSUE THREAD

**Issue by davidhaley** [kiwi-bop/flutter_crashlytics#66]
What are the correct values for setting multi-platform supported priority levels when calling:

`Future<void> log(String msg, {int priority, String tag})`?

The Android logging reference (https://developer.android.com/reference/android/util/Log.html) defines their platform's priority levels:

Verbose = 2
Debug = 3
Info = 4
Warn = 5
Error = 6

The iOS logging reference (https://developer.apple.com/documentation/os/oslogtype) defines their platform's priority levels:

Default (0?)
Info (1?)
Debug (2?)
Error (3?)
Fault (4?)

The example provided for Flutter Crashlytics (https://github.com/kiwi-bop/flutter_crashlytics/blob/master/example/lib/main.dart) uses a priority level of **200**.

Thank you.

**Comment by jaumard** [comment]
Hey @davidhaley ! Priority code come from the `logging` package for dart, you can see them here https://github.com/dart-lang/logging/blob/master/lib/logging.dart#L261 :)

**Comment by davidhaley** [comment]
Hey @jaumard, thank you for responding quickly! That makes a lot of sense.

I am wondering, in the Android documentation, they mention 

> Verbose should never be compiled into an application except during development. Debug logs are compiled in but stripped at runtime. Error, warning and info logs are always kept.

Is there a Dart log level that maps to the Android log level 'VERBOSE'? Or, is this something we even have to take into consideration when setting a priority level?

Thank you.

**Comment by jaumard** [comment]
No problem, I don't really know if we have the same in dart actually... That's a question to ask to the flutter/dart repo ! Quite interesting to know that :)
