### ISSUE TITLE
in iOS -  Fabric called multiple times

### ISSUE THREAD

**Issue by volkangurol** [kiwi-bop/flutter_crashlytics#70]
- I didnt make Fabric setup
- I only use Firebase plugins (flutter_crashlytics, firebase_analytics, firebase_auth vs.)
- In iOS emulator it shows the message: 
[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
Is it a known issue ? or analytics may cause problem sending data ?

- Also in iOS setup enabled (dwarf with dsym file) but in crash reports i can not see error line
Should i run in release mode or missing something ? any help is appreciated.

<img width="744" alt="Screen Shot 2019-03-21 at 16 25 39" src="https://user-images.githubusercontent.com/2510054/54755119-400ad300-4bf6-11e9-957a-44015d02f31d.png">
<img width="742" alt="Screen Shot 2019-03-21 at 16 25 55" src="https://user-images.githubusercontent.com/2510054/54755120-40a36980-4bf6-11e9-9be7-edbdaf4fa20b.png">

- In Android setup there is no kind of this error. (called multiple times)
- In Android crash logs i can see error lines correctly.

<img width="606" alt="Screen Shot 2019-03-21 at 16 27 01" src="https://user-images.githubusercontent.com/2510054/54755103-38e3c500-4bf6-11e9-934d-6dd72bc1083b.png">

**Comment by jaumard** [comment]
`[Fabric] [Fabric +with] called multiple times. ` can you reproduce that with the example app ? 

Line number are coming for the dart exception directly so if the line number is not there I don't think I can do anything about it. But from your screenshot you still have the line number on the title `145` and `144` second line

**Comment by volkangurol** [comment]
thanks for reply, i will dig in. 
As you ve seen android screenshot (the last one) second line of log ot clearly says that error in  home_screen.dart :68 
 (not 144/145 is not related from my code)
İf i found manage to show in ios as well  i will write here.
Thanks

**Comment by gagaJay** [comment]
Im getting the same errors as well.
For 

> Fabric +with] called multiple times.
  
I'm getting it when I click run after the first time.

Im also not getting the right error line on iOS. It is quite confusing.

![image](https://user-images.githubusercontent.com/3827781/55325361-5ad82400-54e1-11e9-9d45-7bdf15a29e66.png)

**Comment by jaumard** [comment]
Should be good with last version normally :)

**Comment by dspoonia7** [comment]
I am also getting this error:

> [Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize

Any idea what's causing this? (I am using flutter_crashlytics and firebase_messaging) and flutter_crashlytics version is 1.0.0.

**Comment by workerbee22** [comment]
Also getting this error across the last 3 versions of firebase_crashlytics

**Comment by thebrianbug** [comment]
Still getting this error also

**Comment by om-ha** [comment]
Any new updates for this error?

**Comment by om-ha** [comment]
I'm getting this issue with `firebase_crashlytics` as well. On iOS.

# Version
firebase_crashlytics: ^0.1.3+3

# Full Log
```
Xcode build done.                                           70.7s
Configuring the default Firebase app...
[Crashlytics] Version 3.14.0 (144)
Configured the default Firebase app __FIRAPP_DEFAULT.
**[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize**
[GoogleDataTransport][I-GDTCOR001006] (/Users/xxxxxxxxxx/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m:59) : There was an error saving the new counter value to disk.
[GoogleDataTransport][I-GDTCOR001006] (/Users/xxxxxxxxxx/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m:59) : There was an error saving the new counter value to disk.
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
```

# Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.5 18F132,
    locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by jaumard** [comment]
`firebase_crashlytics ` is a totally different package

**Comment by om-ha** [comment]
Thanks @jaumard I realized that, but I hoped this would help here, that's why I stated so at the start of my post.

**Comment by aliceathens** [comment]
Same issue here +1

**Comment by okan-oz** [comment]
Same issue here +1

**Comment by pacocd** [comment]
`[Fabric] [Fabric +with] called multiple times.` looks like an error in Fabric SDK.

This log started appearing since Fabric was introduced into a native project and it is initialized from `AppDelegate.application(:, didFinishLaunchingWithOptions:)`.

So, everything should be good even if it appears in our logs.

**Comment by srivasthan** [comment]
In ios/Runner/AppDelegate.swift,

Remove
1. import Firebase
2. Firebase.configure

Reason: Firebase was created by Fabric and we try to initialize for second time. Even though they pointed in docs remove and build the application. (Solution only for Flutter projects)
