### ISSUE TITLE
Official Crashlytics plugin emerged: firebase_crashlytics

### ISSUE THREAD

**Issue by apaatsio** [kiwi-bop/flutter_crashlytics#72]
There's an [official Firebase Crashlytics plugin](https://pub.dartlang.org/packages/firebase_crashlytics) now.

Is flutter_crashlytics going to be deprecated in favor of the official plugin or what's the plan?

**Comment by jaumard** [comment]
I notice that :) but for now it doesn't do a lot, so we'll continue to maintain this one, I guess until the official one is offering a real alternative and make this one obsolete we'll just continue to maintain this one. from what I've understand it may take a while so... keep cool and enjoy 😆

**Comment by jaumard** [comment]
Closing this as no action is needed :)
