### ISSUE TITLE
The 'error' isn't showing in Firebase

### ISSUE THREAD

**Issue by GooSync** [kiwi-bop/flutter_crashlytics#85]
```dart
void main() async {
    FlutterError.onError = (FlutterErrorDetails details) {
      if (!kReleaseMode) {
      FlutterError.dumpErrorToConsole(details);
    } else {
      Zone.current.handleUncaughtError(details.exception, details.stack);
    }
  };
  await FlutterCrashlytics().initialize();

  runZoned<Future<Null>>(() async {
    runApp(MaterialApp(...));
  }, onError: (error, stackTrace) async {
    await FlutterCrashlytics().reportCrash(error, stackTrace, forceCrash: true);
  });
}
```

When a critical error occurs in an application i'm getting the 'null' error in the Fabric
<img width="1243" alt="Снимок экрана 2019-05-03 в 15 31 24" src="https://user-images.githubusercontent.com/12766594/57137479-a750a100-6db8-11e9-9932-f0a5a769c585.png">

But if i'm debugging the application, a see object content of an error and a stackTrace in the `FlutterCrashlytics().reportCrash(error, stackTrace, forceCrash: true)`

Close this issue pls. After some time an error content was appear

**Comment by jaumard** [comment]
Glad It finally worked :)
